<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\Employment;
use App\Models\Service;
use App\Models\Workshop;
use Database\Seeders\Helpers\IndonesianDataHelper;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ServiceSeeder extends Seeder
{
    private const SERVICES_PER_WORKSHOP_MIN = 20;
    private const SERVICES_PER_WORKSHOP_MAX = 50;

    /**
     * Create services for all workshops
     * - Randomly pick customers from global pool
     * - Realistic status distribution
     * - Proper date/time logic
     */
    public function run(): void
    {
        $workshops = Workshop::all();
        $totalServices = 0;
        $serviceCode = 1;

        // Get eligible customer IDs (those who have vehicles)
        // We use query builder to avoid loading models and to prevent "max_allowed_packet" error
        // generated by eager loading huge relationships
        $eligibleCustomerIds = DB::table('vehicles')->distinct()->pluck('customer_uuid')->toArray();

        if (empty($eligibleCustomerIds)) {
            $this->command->error('No vehicles found! Run VehicleSeeder first.');
            return;
        }

        foreach ($workshops as $workshop) {
            // Get mechanics from THIS workshop only
            $mechanics = Employment::where('workshop_uuid', $workshop->id)
                ->where('status', 'active')
                ->whereHas('user') // has valid user
                ->get();

            if ($mechanics->isEmpty()) {
                $this->command->warn("No mechanics for workshop {$workshop->name}, skipping...");
                continue;
            }

            $numServices = rand(self::SERVICES_PER_WORKSHOP_MIN, self::SERVICES_PER_WORKSHOP_MAX);
            $servicesToInsert = [];

            for ($i = 0; $i < $numServices; $i++) {
                // Randomly pick a customer ID from eligible list
                $customerId = $eligibleCustomerIds[array_rand($eligibleCustomerIds)];

                // Get a random vehicle for this customer
                // Using Query Builder for speed and low memory
                $vehicle = DB::table('vehicles')
                    ->where('customer_uuid', $customerId)
                    ->inRandomOrder()
                    ->first();

                if (!$vehicle) {
                    continue;
                }

                $mechanic = $mechanics->random();

                // Service type: 70% walk-in, 30% booking
                $isWalkIn = rand(1, 100) <= 70;
                $type = $isWalkIn ? 'walk-in' : 'regular';

                // Status distribution: 20% pending, 20% in progress, 60% completed
                $statusRand = rand(1, 100);
                if ($statusRand <= 20) {
                    $status = 'pending';
                    $acceptanceStatus = rand(1, 100) <= 80 ? 'pending' : 'decline';
                } elseif ($statusRand <= 40) {
                    $status = 'in progress';
                    $acceptanceStatus = 'accepted';
                } else {
                    $status = 'completed';
                    $acceptanceStatus = 'accepted';
                }

                // Generate realistic dates based on status
                $dates = $this->generateServiceDates($status, $acceptanceStatus);

                $serviceId = Str::uuid()->toString();
                $code = 'SRV-' . str_pad($serviceCode++, 8, '0', STR_PAD_LEFT);
                $category = IndonesianDataHelper::serviceCategories()[array_rand(IndonesianDataHelper::serviceCategories())];
                $validCategories = ['ringan', 'sedang', 'berat', 'maintenance'];
                $serviceCategoryEnum = $validCategories[array_rand($validCategories)];

                $servicesToInsert[] = [
                    'id' => $serviceId,
                    'code' => $code,
                    'workshop_uuid' => $workshop->id,
                    'customer_uuid' => $customerId,
                    'vehicle_uuid' => $vehicle->id,
                    'mechanic_uuid' => $mechanic->id,
                    'name' => $category,
                    'description' => "Service {$category} untuk {$vehicle->brand} {$vehicle->model}",
                    'category_service' => $serviceCategoryEnum,
                    'price' => 0, // Will be in invoice
                    'scheduled_date' => $dates['scheduled_date'],
                    'estimated_time' => $dates['estimated_time'],
                    'status' => $status,
                    'acceptance_status' => $acceptanceStatus,
                    'type' => $type,
                    'reason' => $acceptanceStatus === 'decline' ? 'antrian sedang full' : null,
                    'reason_description' => $acceptanceStatus === 'decline' ? 'Jadwal mekanik penuh' : null,
                    'feedback_mechanic' => $status === 'completed' ? 'Service selesai dengan baik' : null,
                    'accepted_at' => $dates['accepted_at'],
                    'completed_at' => $dates['completed_at'],
                    'created_at' => $dates['created_at'],
                    'updated_at' => now(),
                ];

                $totalServices++;

                // Batch insert every 10 services to prevent max_allowed_packet error
                if (count($servicesToInsert) >= 10) {
                    DB::table('services')->insert($servicesToInsert);
                    $servicesToInsert = [];
                }
            }

            // Insert remaining services for this workshop
            if (!empty($servicesToInsert)) {
                DB::table('services')->insert($servicesToInsert);
            }
        }

        $this->command->info("✓ Created {$totalServices} services");
        $this->command->info("  → Distributed across 500 workshops");
        $this->command->info("  → Customers picked randomly from global pool");

        // Show status distribution
        $this->showStatusDistribution();
    }

    /**
     * Generate realistic dates based on service status
     */
    private function generateServiceDates(string $status, string $acceptanceStatus): array
    {
        $today = now();

        if ($status === 'pending') {
            // Pending services: scheduled for today or near future
            if (rand(1, 100) <= 50) {
                // 50% are TODAY (for demo/testing)
                $scheduledDate = $today->copy();
            } else {
                // 50% are upcoming (next 1-7 days)
                $scheduledDate = $today->copy()->addDays(rand(1, 7));
            }

            return [
                'scheduled_date' => $scheduledDate->format('Y-m-d'),
                'estimated_time' => $scheduledDate->copy()->addHours(rand(2, 6))->format('Y-m-d H:i:s'),
                'accepted_at' => null,
                'completed_at' => null,
                'created_at' => $today->copy()->subHours(rand(1, 48)),
            ];
        }

        if ($status === 'in progress') {
            // In progress: started 1-5 days ago, accepted
            $scheduledDate = $today->copy()->subDays(rand(1, 5));
            $acceptedAt = $scheduledDate->copy()->addHours(rand(1, 3));

            return [
                'scheduled_date' => $scheduledDate->format('Y-m-d'),
                'estimated_time' => $scheduledDate->copy()->addHours(rand(3, 8))->format('Y-m-d H:i:s'),
                'accepted_at' => $acceptedAt->format('Y-m-d H:i:s'),
                'completed_at' => null,
                'created_at' => $scheduledDate->copy()->subDays(rand(1, 2)),
            ];
        }

        if ($status === 'completed') {
            // Completed: finished 1-90 days ago
            $completedDate = $today->copy()->subDays(rand(1, 90));
            $scheduledDate = $completedDate->copy()->subDays(rand(1, 3));
            $acceptedAt = $scheduledDate->copy()->addHours(rand(1, 6));

            return [
                'scheduled_date' => $scheduledDate->format('Y-m-d'),
                'estimated_time' => $scheduledDate->copy()->addHours(rand(2, 6))->format('Y-m-d H:i:s'),
                'accepted_at' => $acceptedAt->format('Y-m-d H:i:s'),
                'completed_at' => $completedDate->format('Y-m-d H:i:s'),
                'created_at' => $scheduledDate->copy()->subDays(rand(1, 5)),
            ];
        }

        // Fallback
        return [
            'scheduled_date' => $today->format('Y-m-d'),
            'estimated_time' => $today->copy()->addHours(2)->format('Y-m-d H:i:s'),
            'accepted_at' => null,
            'completed_at' => null,
            'created_at' => $today,
        ];
    }

    /**
     * Show status distribution statistics
     */
    private function showStatusDistribution(): void
    {
        $stats = DB::table('services')
            ->select('status', DB::raw('COUNT(*) as count'))
            ->groupBy('status')
            ->get();

        $this->command->newLine();
        $this->command->info('📊 Service Status Distribution:');

        $statusTable = [];
        foreach ($stats as $stat) {
            $statusTable[] = [$stat->status, $stat->count];
        }
        $this->command->table(['Status', 'Count'], $statusTable);
    }
}
